# Generated by Django 6.0.1 on 2026-02-03 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolform', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={},
        ),
    ]
