# Generated by Django 6.0.1 on 2026-02-03 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolform', '0002_alter_student_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='created_at',
        ),
    ]
